### ISSUE TITLE
Can the @Middleware annotation accept custom params?

### ISSUE THREAD

**Issue by kirkbushell** [LaravelCollective/annotations#16]
I'd like to be able to pass some configuration to a piece of middleware I've written. Is it possible to do this at all?

Something like:

```
@Middleware("SomeMiddleware", param="value")
```

?

**Comment by RobinMalfait** [comment]
Hmmm, why would you set that? can't you just set an attribute on the class?

``` php
class SomeController extends Controller {
   private $param = "value";
}
```

**Comment by kirkbushell** [comment]
@RobinMalfait because I want a specific piece of middleware to have a certain configurable option. Having it on the controller doesn't help. It's the middleware that needs to have it :)

**Comment by adamgoose** [comment]
You're not the only one who has requested this functionality. Currently, this is not possible because Middleware only accepts the request object. I have a couple ideas in the pipeline since I have recently implemented something _similar_. I'm hoping to make annotation customization more flexible, which could help you solve this.
