### ISSUE TITLE
annotation route cache

### ISSUE THREAD

**Issue by terrylow** [LaravelCollective/annotations#42]
I have some simple annotations setup with laravel 5.2

`@Get("/", as="home")`
`@Get("/about", as="about")`
`@Get("/contact", as="contact")`

routes are scanned and routes show in route:list command, but after perform a route:cache, no route is found and causes a NotFoundHttpException. is this an intended behaviors?

**Comment by tshafer** [comment]
Is this still an issue?

**Comment by kohkimakimoto** [comment]
I've had same issue. In my case, the issue caused by removing `App\Providers\RouteServiceProvider::class` from `config/app.php`. By using annotation, I thought that `App\Providers\RouteServiceProvider` was no longer used,  because this provider did not load any routing files like `routes/web.php`.

But, in the production environment that loads routing cache, we need to use `App\Providers\RouteServiceProvider`. This provider loads the cached routes by calling `boot` method.

see https://github.com/laravel/framework/blob/v5.6.14/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L31

Check your `config/app.php`.

```php
    'providers' => [
        //... 
        App\Providers\AnnotationsServiceProvider::class,
        // We need RouteServiceProvider to load routing cache!
        App\Providers\RouteServiceProvider::class,
        //...
    ],
````

**Comment by loonytoons** [comment]
I've added a comment to the readme to clarify that the RouteServiceProvider is still required
