### ISSUE TITLE
please  release 5.7

### ISSUE THREAD

**Issue by wujunze** [LaravelCollective/annotations#78]
please  release 5.7

**Comment by johntimothybailey** [comment]
@wujunze I created a pull request #79. That said, not sure how @tshafer and the other maintainers would like Pull Requests submitted. So #79 may need to be closed an new one created.

**Comment by EmilMoe** [comment]
This is really bad that it's such a slow progress

**Comment by tshafer** [comment]
I am no longer a active maintainer.

**Comment by EmilMoe** [comment]
Does this mean that the library will not get updates @tshafer

**Comment by tshafer** [comment]
Not unless the other active maintainers do it.


—
Tom Shafer

From: Emil Moe <notifications@github.com> <notifications@github.com>
Reply: LaravelCollective/annotations
<reply@reply.github.com>
<reply@reply.github.com>
Date: October 9, 2018 at 8:07:17 AM
To: LaravelCollective/annotations <annotations@noreply.github.com>
<annotations@noreply.github.com>
Cc: Tom Shafer <tj@tjshafer.com> <tj@tjshafer.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [LaravelCollective/annotations] please release 5.7 (#78)

Does this mean that the library will not get updates @tshafer
<https://github.com/tshafer>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LaravelCollective/annotations/issues/78#issuecomment-428229813>,
or mute the thread

**Comment by EmilMoe** [comment]
Thanks for the reply @tshafer Now I can better justify my time towards taking down the annotations.

**Comment by loonytoons** [comment]
5.7 is now released, 5.8 incoming soon
